worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;
    access_log off;

    server {
        listen 8443 ssl;
        server_name _;

        ssl_certificate     /opt/eec/server/tls/server.crt;
        ssl_certificate_key /opt/eec/server/tls/server.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Enable HTTP/2
        http2 on;

        root /opt/eec/server/assets;

        location /bulk/ {
            autoindex off;
        }

        location /hls/ {
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
        }

        location /hls.key {
            alias /opt/eec/server/tls/hls.key;
        }

        location /status {
            stub_status;
        }
    }
}
